stages:
  - build
  - unit_tests
  - sonar

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/".insteadOf "gitlab.dracoon.com:"
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/ios/client/sdk-swift-crypto-sonar.git
  - cd sdk-swift-crypto-sonar
  - sh setup.sh
  - cd ..

build:
  dependencies: []
  stage: build
  artifacts:
    paths:
      - ./compile_commands.json
  script:
    - bundle exec fastlane build
  tags:
    - darwin/arm64
    - ios-build

unit_tests:
  dependencies: []
  stage: unit_tests
  artifacts:
    paths:
      - TestResults/Logs/Test/*.xcresult
  script:
    - bundle exec fastlane runUnitTests
    - cp sdk-swift-crypto-sonar/printCodeCoverage.sh TestResults/Logs/Test/
    - cd TestResults/Logs/Test/
    - ./printCodeCoverage.sh
    - cd ../../../
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - darwin/arm64
    - ios-build

sonar:
  stage: sonar
  artifacts:
    paths:
      - ./sonar-project.properties
  script:
    - bundle exec fastlane runSonar
  tags:
    - darwin/arm64
    - ios-build
