stages:
  - build
  - unit_tests
 # - sonar

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/ios/client/sdk-swift-crypto-sonar.git
  - sh sdk-swift-crypto-sonar/setup.sh

build:
  dependencies: []
  stage: build
 # artifacts:
 #   paths:
 #     - ./compile_commands.json
  script:
    - bundle exec fastlane build
    - ([ -e "compile_commands.json" ] && echo "compilation db file exists" || echo "compilation db file does not exist")
  tags:
    - darwin/arm64
    - ios-build

unit_tests:
  dependencies: []
  stage: unit_tests
  #artifacts:
  #  paths:
  #    - TestResults/Logs/Test/*.xcresult
  script:
    - bundle exec fastlane runUnitTests
    - cp sdk-swift-crypto-sonar/printCodeCoverage.sh TestResults/Logs/Test/
    - sh TestResults/Logs/Test/printCodeCoverage.sh
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - darwin/arm64
    - ios-build

#sonar:
#  stage: sonar
#  artifacts:
#    paths:
#      - ./sonar-project.properties
#  script:
#    - bundle exec fastlane runSonar
#  tags:
#    - darwin/arm64
#    - ios-build
