stages:
  - build
  - unit_tests
  - sonar

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dracoon.com/dracoon/ios/client/sdk-swift-crypto-sonar.git
  - sh sdk-swift-crypto-sonar/setup.sh
  - sh /opt/gitlab/Library/cleanupArtifacts.sh
  - mkdir /opt/gitlab/Library/Artifacts/${CI_JOB_ID}

build:
  dependencies: []
  stage: build
  script:
    - bundle exec fastlane build
    - ([ -e "compile_commands.json" ] && echo "compilation db file exists" || echo "compilation db file does not exist")
    - ls -l compile_commands.json
    - cp compile_commands.json /opt/gitlab/Library/Artifacts/${CI_JOB_ID}
  #artifacts:
  #  paths:
  #    - $CI_PROJECT_DIR/compile_commands.json
  tags:
    - darwin/arm64
    - ios-build

unit_tests:
  dependencies: []
  stage: unit_tests
  #artifacts:
  #  paths:
  #    - TestResults/Logs/Test/*.xcresult
  script:
    - bundle exec fastlane runUnitTests
    - cp sdk-swift-crypto-sonar/printCodeCoverage.sh TestResults/Logs/Test/
    - sh TestResults/Logs/Test/printCodeCoverage.sh
    - cp -r TestResults /opt/gitlab/Library/Artifacts/${CI_JOB_ID}
  coverage: '/Code coverage: \d+\.\d+/'
  tags:
    - darwin/arm64
    - ios-build

sonar:
  stage: sonar
  dependencies:
    - build
    - unit_tests
  #artifacts:
  #  paths:
  #    - ./sonar-project.properties
  script:
    - cp /opt/gitlab/Library/Artifacts/${CI_JOB_ID}/compile_commands.json .
    - cp -r /opt/gitlab/Library/Artifacts/${CI_JOB_ID}/TestResults .
    - bundle exec fastlane runSonar
  tags:
    - darwin/arm64
    - ios-build
